### ISSUE TITLE
How to transform from latlng to left, bottom, right, top?

### ISSUE THREAD

**Issue by shunnokw** [mapsquare/mbtiles-generator#2]
For example, I have the boundary in Latlng:
```
swPanBoundary: LatLng(52.492205, 13.282081),
nePanBoundary: LatLng(52.540084, 13.527795), 
```
How can I transform it to left, bottom, right, top to fit in the API?

Thank you

**Comment by loicortola** [comment]
Hello!
Did you manage it?
Basically, sw = bottom-left, ne = top right on the Web Mercator projection.
For two points 1 and 2 of coordinates (Lat1, Lon1), (Lat2, Lon2)
south = min(Lat1, Lat2)
left = min(Lon1, Lon2)

etc...

^^

Cheers
